### PR TITLE
Linux support

### PR DESCRIPTION
**Pull request by LukasBombach**
Adds support for Linux using `DBus` and `Bluez`.

Adds dependency to the packages `dbus` and `md5`

### CODE REVIEW

**Review by marksyzm — COMMENTED** [review]
Excellent!! You shall be praised :D

**Comment by atrovato** [comment]
Hi, do you need any help on this point?
It's an awaited compatibility 😄

**Comment by LukasBombach** [comment]
Sorry, I have so many things to do IRL right now, I did not realize people are actively waiting for this. I'm gonna pick this up again now.

**Comment by atrovato** [comment]
Thank you, real life is more important,  let us know when you start again.

**Comment by readeral** [comment]
You can bet that people are really hungry for this project, given Noble's lack of development. Anything we can do to help to progress this development please do advise! Really appreciate your hard work so far.

**Comment by LukasBombach** [comment]
Ok, imma pick up work on this again

**Comment by vekexasia** [comment]
Looking forward to see this working as noble is basically useless for my usecase.

**Comment by LukasBombach** [comment]
just started picking this up again

**Comment by vekexasia** [comment]
Hello @LukasBombach Thanks for the great work. Do you need any help/tester ?

**Comment by LukasBombach** [comment]
Thanks! I'd be happy to get feedback of things that work / do not work when I can release this :)

**Comment by readeral** [comment]
Good to know you're keen for testers @LukasBombach  - I'm likewise keen to help and/or test.

**Comment by vekexasia** [comment]
Hello @LukasBombach thanks for the solid progress on this. Do you have any ETA for when this might be tested?

**Comment by buildog** [comment]
@LukasBombach is it already testable on Raspbian ? 
**EDIT**:
Progress state https://github.com/LukasBombach/sblendid/projects/3 (write, read, notify isn't yet supported)

**Comment by LukasBombach** [comment]
@buildog that is correct, sorry, it's not ready yet. I am having a hard time finding the time right now, but seeing the people commenting here motivates me. I am working on this in tiny steps right now.

@vekexasia sorry no ETA as things are tight right now. I am expecting twins soon and then there is, of course, Corona.

**Comment by readeral** [comment]
@LukasBombach really appreciate the incremental (but monumental) efforts you're putting in. If there's any way you can farm out small sections that doesn't create more work for yourself, please do let us know.

**Comment by atrovato** [comment]
Hi, why this is now closed? Is it abandonned?

**Comment by LukasBombach** [comment]
@atrovato I am actually rebooting the project

https://github.com/LukasBombach/web-bluetooth-node

I am trying to imlpement web-bluetooth for node, but this time I will cut the BS and will go native instead. By this I mean, for macOS, I am actually implementing a native node module using Objective-C++, for Windows and Linux I will do the same using pure C++.

These native node modules will be very thin and just proxy JavaScript calls to the operating systems' APIs. On top top of that I will implement the web-bluetooth spec for node js and on top of that I will implement Sblendid.

But for now you should probably watch https://github.com/LukasBombach/web-bluetooth-node instead of this PR

**Pull request closed without merging**
